### PR TITLE
Enable community partners section

### PR DESCRIPTION
**Pull request by TeeWrath**
- Enabled community partner section
- Issue #31

### CODE REVIEW

**Comment by bhansa** [comment]
Please squash the commits. Add a separator between sections.

There is not much visual space between the sections.

image

**Comment by anistark** [comment]
Screenshot 2024-06-03 at 5 20 03 PM

Remove previous content except FOSS United.

Buttons:

- Become a Partner should take them to [form link](https://bit.ly/cmtp).
- Second button can be renamed as Read more and pointed to [navigator](https://navigator.in.pycon.org/en/latest/participate/community-partner.html).

**Comment by anistark** [comment]
I guess this needs update. @TeeWrath can you make changes?

**Comment by TeeWrath** [comment]
@anistark sure, by when do you need the updates ?

**Comment by anistark** [comment]
> @anistark sure, by when do you need the updates ?

as soon as possible.

We don't need to put any links to become partner anymore. And let's not call it community partners too. We can call it "participating communities" maybe.

cc: @bhansa

**Comment by anistark** [comment]
This is done. Closing the PR.

**Pull request closed without merging**
