### PR TITLE
Contributing Guide and Project Setup Guide

### PR DESCRIPTION
**Pull request by TeeWrath**
- For issue #12

### CODE REVIEW

**Review by anistark — CHANGES_REQUESTED** [review]
It doesn't have setup instructions.

**Review by bhansa — APPROVED** [review]

**Review by bhansa — COMMENTED** [review]
Add steps to clone the repo and then start with 11ty setup.

**Comment by TeeWrath** [comment]
@bhansa have added the changes you suggested. Kindly check and let me know if any changes required

**Comment by anistark** [comment]
> @bhansa have added the changes you suggested. Kindly check and let me know if any changes required

Still no setup instructions.

**Comment by TeeWrath** [comment]
@anistark Hey 👋🏻 
Umm please check this, let me know if any changes required ?
Screenshot from 2024-05-06 00-13-24

**Comment by anistark** [comment]
> @anistark Hey 👋🏻 Umm please check this, let me know if any changes required ? 

Setup instruction shouldn't be in contributing guidelines ideally. Better in readme I guess?

**Comment by TeeWrath** [comment]
@anistark check now

**Review by bhansa — APPROVED** [review]

**Pull request merged**
