### PR TITLE
added anchor

### LINKED ISSUE #44: Have ids for the headings on FAQ page
We usually need to send specific FAQs to speakers and attendees. Having an id on all these headings would help with that. 
The ids don't need to be automatically generated, could be simple human readable, manually added ones as well.

I'm referring to the id attribute on the h tags. This will help to link to sections like `/faq/#buying-tickets`.

We will need this in coming week by Wednesday or so, as we send out acceptance emails to speakers. 

cc @bhansa

### PR DESCRIPTION
**Pull request by kybrdbnd**
resolves #44

### CODE REVIEW

**Review by SaptakS — CHANGES_REQUESTED** [review]
Thanks for the PR! This is slightly problematic though, because according to [WCAG SC 2.4.4](https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context.html), links should have an accessible name.

I feel the anchors are not actually visible. I think the correct markup for it should be something like this:

```html
<a class="anchor">
  <span aria-hidden="true">#</span>
  <span>anchor</span>
</a>
<h3 id="pycon">What is PyCon India?</h3>
```

This ensures the id is on heading, and the anchor button allows you to click and copy the anchored links. Also, ensures that the anchor has proper name.

For adding the id to heading, I would recommend checking out https://www.npmjs.com/package/@orchidjs/eleventy-plugin-ids or https://syntackle.com/blog/adding-custom-anchors-to-headings-in-markdown-eleventy-3NxBhIJO2OIr4XOj5LKc/

**Comment by anistark** [comment]
@kybrdbnd Please update the fixes and lets get it merged.

**Comment by kybrdbnd** [comment]
anchor element is clearly visible

image

and the links are generated when clicked on it: http://localhost:8080/2024/faq/#pycon

Apologies if I have misunderstood the requirement @SaptakS

**Comment by SaptakS** [comment]
image

So you added `<a class="anchor" id="pycon"></a>` which are showing inside the `<p>` tag as empty links, which don't really do anything apart from providing an id to anchor to.

**Comment by SaptakS** [comment]
What I was suggesting to use instead is:
image

Which should show an anchor link before the heading for the anchor to the heading id. 

You can also add the anchor link inside the heading element after the heading text also to make it look something like this:
image

The HTML for that would be something like:
image

Only thing is, in both cases, to add heading in markdown, you need to install some extra markdown-it plugins. Let me know if you need any assistance. Happy to help.

**Comment by kybrdbnd** [comment]
i hope these anchors would work

image

**Review by SaptakS — APPROVED** [review]
This uses a separate dependency, but the end result looks good to me. So approving.

**Pull request merged**
